In [ ]:
from pyAudioAnalysis import audioTrainTest as aT

In [41]:
paths_train = [''] * 10
for i in range(len(paths_train)):
    paths_train[i] = 'dataset/'+str(i)

aT.extract_features_and_train(paths_train, 1.0, 1.0, 0.05, 0.05, 'randomforest', '0_9Classes_RandomForest')

Analyzing file 1 of 1200: dataset/0\0_02_0.wav
Analyzing file 2 of 1200: dataset/0\0_02_1.wav
Analyzing file 3 of 1200: dataset/0\0_02_10.wav
Analyzing file 4 of 1200: dataset/0\0_02_11.wav
Analyzing file 5 of 1200: dataset/0\0_02_12.wav
Analyzing file 6 of 1200: dataset/0\0_02_13.wav
Analyzing file 7 of 1200: dataset/0\0_02_14.wav
Analyzing file 8 of 1200: dataset/0\0_02_15.wav
Analyzing file 9 of 1200: dataset/0\0_02_16.wav
Analyzing file 10 of 1200: dataset/0\0_02_17.wav
Analyzing file 11 of 1200: dataset/0\0_02_18.wav
Analyzing file 12 of 1200: dataset/0\0_02_19.wav
Analyzing file 13 of 1200: dataset/0\0_02_2.wav
Analyzing file 14 of 1200: dataset/0\0_02_20.wav
Analyzing file 15 of 1200: dataset/0\0_02_21.wav
Analyzing file 16 of 1200: dataset/0\0_02_22.wav
Analyzing file 17 of 1200: dataset/0\0_02_23.wav
Analyzing file 18 of 1200: dataset/0\0_02_24.wav
Analyzing file 19 of 1200: dataset/0\0_02_25.wav
Analyzing file 20 of 1200: dataset/0\0_02_26.wav
Analyzing file 21 of 1200: datas

In [42]:
paths_test = [''] * 10
for i in range(len(paths_train)):
    paths_test[i] = 'dataset/'+str(i)
    
aT.evaluate_model_for_folders(paths_test, '0_9Classes_RandomForest', 'randomforest', positive_class='dataset/0')

[[12  0  1 14  3  2  0 18  0  0]
 [ 0 45  0  0  2  0  0  0  0  3]
 [ 0  0 50  0  0  0  0  0  0  0]
 [ 1  0 12 36  0  0  0  0  0  1]
 [ 0  0  0  0 50  0  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 0  0  0  2  0  0 48  0  0  0]
 [ 0  0  0  0  0  0  0 50  0  0]
 [ 0  0  1  3  0  0  0  0 46  0]
 [ 1  2  0  2  0  0  0  0  0 45]]
[np.float64(0.24), np.float64(0.9), np.float64(1.0), np.float64(0.72), np.float64(1.0), np.float64(1.0), np.float64(0.96), np.float64(1.0), np.float64(0.92), np.float64(0.9)] [np.float64(0.8571428571428571), np.float64(0.9574468085106383), np.float64(0.78125), np.float64(0.631578947368421), np.float64(0.9090909090909091), np.float64(0.9615384615384616), np.float64(1.0), np.float64(0.7352941176470589), np.float64(1.0), np.float64(0.9183673469387755)] [np.float64(0.375), np.float64(0.9278350515463918), np.float64(0.8771929824561403), np.float64(0.6728971962616822), np.float64(0.9523809523809523), np.float64(0.9803921568627451), np.float64(0.9795918367346939), np.

(array([[12,  0,  1, 14,  3,  2,  0, 18,  0,  0],
        [ 0, 45,  0,  0,  2,  0,  0,  0,  0,  3],
        [ 0,  0, 50,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  0, 12, 36,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0, 50,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 50,  0,  0,  0,  0],
        [ 0,  0,  0,  2,  0,  0, 48,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0, 50,  0,  0],
        [ 0,  0,  1,  3,  0,  0,  0,  0, 46,  0],
        [ 1,  2,  0,  2,  0,  0,  0,  0,  0, 45]]),
 array([0.   , 0.002, 0.004, 0.006, 0.008, 0.01 , 0.012, 0.014, 0.016,
        0.018, 0.02 , 0.022, 0.024, 0.026, 0.028, 0.03 , 0.032, 0.034,
        0.036, 0.038, 0.04 , 0.042, 0.044, 0.046, 0.048, 0.05 , 0.052,
        0.054, 0.056, 0.058, 0.06 , 0.062, 0.064, 0.066, 0.068, 0.07 ,
        0.072, 0.074, 0.076, 0.078, 0.08 , 0.082, 0.084, 0.086, 0.088,
        0.09 , 0.092, 0.094, 0.096, 0.098, 0.1  , 0.102, 0.104, 0.106,
        0.108, 0.11 , 0.112, 0.114, 0.116, 0.118, 0.122, 0.124, 0.126,
 